[package]
name = "rust-weather"
version = "0.1.0"
authors = ["ggljzr <gogo.lejzr@gmail.com>"]

[dependencies]
futures = "0.1"
hyper = "0.11"
hyper-tls = "0.1.3"
tokio-core = "0.1"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"